lazyscribe/lazyscribe

- docs/how-to/tabular.rst
- lazyscribe/project.py
- setup.cfg
- tests/test_project.py
- tutorials/basic.py
In this PR, I've added a ``to_tabular`` method to `Project` to help users create experiment and test-level dataframes:
```python
import pandas as pd
from lazyscribe import Project
project = Project(..., mode="r")
experiments, tests = project.to_tabular()
exp_df = pd.DataFrame(experiments)
exp_df.columns = pd.MultiIndex.from_tuples(exp_df.columns)
```
> Experiment and test lists for easy conversion to pandas

- pyproject.toml
Package build and upload failed for v0.3.2 because of an error with the description content type. I used [this section in the setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata) to update the dynamic metadata for the `readme` field with the right content type.
> Fixing the content-type for the readme

- lazyscribe/project.py
Using this on a project with a fairly deep dependency tree. Project load times blow up fairly quickly with both number of experiments in each project and number of projects in the tree.
This fix greatly reduced my load/initialization times. In the deepest part of my tree, I went from ~10min to about 0.25s.
Basically if a project contains multiple experiments that have overlapping project dependencies, this stores the upstream projects in a dictionary and refrains from opening/loading the same project multiple times.
> Removing Duplicate Project Loads from Dependencies

- .readthedocs.yaml
Since we migrated to the `pyproject.toml`, we haven't been able to publish updated documentation to readthedocs. I'm trying this configuration based on their docs.
> Trying a new readthedocs configuration

- .readthedocs.yaml
This PR does not represent a new release. I am opening a PR to the `main` branch to ensure we have updated documentation on RTD.
Our GitHub workflow should not trigger a new version on PyPI since we have it set to trigger on new GitHub releases.
> Fixing our readthedocs configuration

- .github/workflows/docs.yml
Title. Build and deploy are separate jobs as recommended by GitHub. Will build docs on every PR, but only deploy on `release: created` or manually with `workflow_dispatch`.
To enable publishing GitHub Pages directly from an action, a repository admin will have to enable that setting in the repository settings. We _may_ have to merge to main for the initial build for `workflow_dispatch` trigger.
> Add docs workflow to build and deploy to GitHub Pages

- lazyscribe/test.py
See https://github.com/lazyscribe/lazyscribe/issues/28, p. 11.
> Tell pytest the `Test` is not a Python test class

- .github/workflows/publish-package.yml
In this PR, I have updated the publish workflow based on [the PyPA GitHub action](https://github.com/pypa/gh-action-pypi-publish). This involved updating our PyPI page to add this repository as a trusted publisher.
> Updating the publish workflow

- docs/sg_execution_times.rst
- lazyscribe/artifacts/joblib.py
- lazyscribe/project.py
- tests/test_handlers.py
- tests/test_project.py
#28
In this PR, I have modified the test-level tabular output from `Project.to_tabular` so the experiment information is explicitly prefixed. I have also added error handling for the `JoblibArtifact`. @kuraga pointed out that some _very_ common objects (e.g. `numpy.array`) do not have the `__module__` attribute. I'm not sure how to get around that for the information we need, so I added error handling. Users can get around the error by specifying a `package` argument to the constructor.
> Modifying the `Project.to_tabular` output for test-level data and adding error handling for `JoblibArtifact.construct`

- docs/how-to/custom-artifact.rst
- lazyscribe/__init__.py
- lazyscribe/artifacts/__init__.py
- lazyscribe/artifacts/base.py
- lazyscribe/artifacts/joblib.py
- lazyscribe/artifacts/json.py
- lazyscribe/experiment.py
- lazyscribe/linked.py
- lazyscribe/prefect/__init__.py
- lazyscribe/prefect/experiment.py
- lazyscribe/prefect/project.py
- lazyscribe/project.py
- lazyscribe/test.py
- pyproject.toml
- tests/conftest.py
- tutorials/prefect.py
There were some deprecations in 3.9 (our minimal version now):
https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections
> Simplify `typing` annotations

- docs/how-to/artifact.rst
- docs/how-to/custom-artifact.rst
- lazyscribe/artifacts/yaml.py
- pyproject.toml
- tests/test_handlers.py
In this PR, I've added an artifact handler using PyYAML. Users can use pass-through args to choose which loader (or dumper) they want to use on logging or loading. I have also changed the how-to guide for custom artifacts to a `TextArtifact` as YAML is now built-in.
> feat: Add YAML artifact handler

- docs/how-to/custom-artifact.rst
- lazyscribe/_utils.py
- lazyscribe/artifacts/joblib.py
- lazyscribe/artifacts/json.py
- lazyscribe/artifacts/yaml.py
- lazyscribe/experiment.py
- lazyscribe/repository.py
- tests/conftest.py
- tests/test_experiment.py
- tests/test_handlers.py
- tests/test_prefect.py
- tests/test_project.py
- tests/test_utils.py
- New custom function to return naive datetime now but in UTC.
- Use new custom util function everywhere where we used to use `datetime.now`
- Time travel everywhere where appropriate in tests.
> Use UTC everywhere

- docs/how-to/custom-artifact.rst
There is `lazyscribe.Project.log()` only.
> Update custom-artifact.rst: fix code example

- lazyscribe/repository.py
After merging of #81, some my comments left untouched.
This PR fixes them in my way.
Each modification is contained in a separate (descriptive) commit (for discussion convenience).
Comments addressed in this PR:
* https://github.com/lazyscribe/lazyscribe/pull/81#discussion_r1943179535 (a7da8622b57584b54daf42909b1ac1c2bc4c2ae0),
* https://github.com/lazyscribe/lazyscribe/pull/81#discussion_r1940992449 (7fc01e012b2ea42931a738f685bc8ddac48420b7),
* https://github.com/lazyscribe/lazyscribe/pull/81#discussion_r1943206209 (e38fb87dac0b0ae0bcac6c2f0056651853d81393),
* https://github.com/lazyscribe/lazyscribe/pull/81#discussion_r1928836161 (cfc5e5e0c7dd88180625c75e334916e65d8695ad),
* https://github.com/lazyscribe/lazyscribe/pull/81#discussion_r1940954195 …
> Fix from #84 @kuraga's comments

- .pre-commit-config.yaml
- lazyscribe/repository.py
- tests/test_repository.py
In v0.7.0, we have the following bug:
```python
from lazyscribe.repository import Repository
repo = Repository()
repo.log_artifact("my-dict", {"a": 1}, handler="json")
repo.save()  # Everything is good so far
repo = Repository(mode="a")
repo.log_artifact("my-dict-2", {"b": 2}, handler="json")
repo.save()  # No error is thrown, but now the "my-dict" JSON file is null
```
this is because we were saving every artifact, regardless of whether it had been loaded by the user.
In this PR, I have copied the logic from `Project.save` to only touch the filesystem when the artifact is newer than the file.
> fix: adding a check to ensure existing artifacts are not overwritten with null data and removing the w+ mode

- docs/how-to/custom-artifact.rst
- lazyscribe/_utils.py
- lazyscribe/artifacts/base.py
- lazyscribe/artifacts/joblib.py
- lazyscribe/artifacts/json.py
- lazyscribe/artifacts/yaml.py
- lazyscribe/experiment.py
- lazyscribe/project.py
- lazyscribe/repository.py
- tests/conftest.py
- tests/test_experiment.py
- tests/test_handlers.py
- tests/test_project.py
- tests/test_repository.py
s/o @kuraga in [this comment](https://github.com/lazyscribe/lazyscribe/pull/96#issuecomment-2660204084).
In this PR, I have added the `dirty` flag that @kuraga suggested in #96. Essentially, artifacts are only written to disk on `save` when the flag is `True`. It is only `True` when constructed through the `log_artifact` methods in `Repository` and `Experiment`.
On the question of whether it's a "breaking change" -- I made two adjustments to the test suite:
1. Updating the `construct` method signature for the test handler,
2. Updating our manual construction of the handler in a project-level test.
I have also implemented the `dirty` flag for experiments. With this feature, we can delete the `snapshot` attribute of `lazyscribe.Project`.
> feat!: using a new `dirty` flag to describe whether an artifact or experiment needs to be persisted

- lazyscribe/project.py
- tests/test_experiment.py
- tests/test_project.py
Removes duplication of directory structure when string path is passed on initialization of a `Project`.
Closes: #105.
> fix!: handle string project filepaths

- README.md
- lazyscribe/artifacts/__init__.py
- lazyscribe/artifacts/joblib.py
- lazyscribe/exception.py
- lazyscribe/experiment.py
- lazyscribe/project.py
- lazyscribe/repository.py
- tests/test_experiment.py
- tests/test_handlers.py
- tests/test_project.py
- tests/test_repository.py
This PR replaces the generic `RuntimeError` with custom errors so that users can catch our exceptions directly without matching other errors..
> feat!: Replace `RuntimeError` with custom errors

- dev-requirements.txt
- lazyscribe/repository.py
- pyproject.toml
- tests/test_repository.py
In this PR, I've added an argument to `load_artifact` called `match`. If the user provides a `str` or `datetime.datetime` object for `version` along with `match="asof"`, they will retrieve the latest version of the artifact as of that given date. I have also added a method for retrieving artifact metadata, as this can be helpful when parsing environment constraints.
> feat(repository): `asof` version matching to allow users to get the latest version of an artifact as of a given datetime

- docs/how-to/version-artifacts.rst
- docs/index.rst
- lazyscribe/exception.py
- lazyscribe/experiment.py
- lazyscribe/project.py
- lazyscribe/repository.py
- tests/test_promotion.py
In this PR, I've added a method to the `Experiment` class that allows users to directly promote a logged artifact to a `Repository`. There are two main branches of logic here:
1. **The Artifact is `dirty`**: in this case, the artifact will need to be saved to the file system regardless. We can just append the artifact handler to the list in `Repository`.
2. **The Artifact is not `dirty`**: here, the artifact exists on the file system and does not need to be overwritten. So, we can append the artifact handler and copy the file. Crucially, we need to call `Repository.save`; without this call, the user may end up with an artifact file in their directory structure that is not associated with anything in the `repository.json` file.
cc @Dike-LAN @valdezt
> feat: adding the ability for users to promote an artifact from an experiment to a repository

- lazyscribe/repository.py
- tests/test_repository.py
- There is no "a read-only artifact".
- `mode="a"` is not relevant to the repository.
Closes: https://github.com/lazyscribe/lazyscribe/issues/104
> fix(repository): `repository.Repository`: fix `mode` handling

- lazyscribe/project.py
- tests/test_project.py
For experiments of the same name, default to retrieving the last saved version. 
Added warning logs to check if `last_updated` timestamp was manually modified such that the last saved experiment does NOT have the maximum `last_updated` timestamp.
Resolves #138
> Update to get latest saved experiment based on short_slug

- lazyscribe/project.py
- tests/test_project.py
For experiments of the same name, default to retrieving the last saved version.
Added warning logs to check if last_updated timestamp was manually modified such that the last saved experiment does NOT have the maximum last_updated timestamp.
Fixes #138
> feat(project):  return the last experiment with the matched short_slug instead of the first
